// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAFv2IcipLj9LDQGfdE2buKhg0-iLz3-7g',
    appId: '1:1075151975040:web:96d3834eabd6321ff92c65',
    messagingSenderId: '1075151975040',
    projectId: 'amasya-son-dakika',
    authDomain: 'amasya-son-dakika.firebaseapp.com',
    storageBucket: 'amasya-son-dakika.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCvBBkaAq-gw4hE4VsXdWJqELtYEks4NCI',
    appId: '1:1075151975040:android:1353fba2c92f8764f92c65',
    messagingSenderId: '1075151975040',
    projectId: 'amasya-son-dakika',
    storageBucket: 'amasya-son-dakika.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBoRt9OlVQISbZkoqhpYravDdzP9bKRWNk',
    appId: '1:1075151975040:ios:0cd19d0ae6d9db17f92c65',
    messagingSenderId: '1075151975040',
    projectId: 'amasya-son-dakika',
    storageBucket: 'amasya-son-dakika.firebasestorage.app',
    iosBundleId: 'com.example.amasyasondakika',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBoRt9OlVQISbZkoqhpYravDdzP9bKRWNk',
    appId: '1:1075151975040:ios:0cd19d0ae6d9db17f92c65',
    messagingSenderId: '1075151975040',
    projectId: 'amasya-son-dakika',
    storageBucket: 'amasya-son-dakika.firebasestorage.app',
    iosBundleId: 'com.example.amasyasondakika',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAFv2IcipLj9LDQGfdE2buKhg0-iLz3-7g',
    appId: '1:1075151975040:web:111827d508329e85f92c65',
    messagingSenderId: '1075151975040',
    projectId: 'amasya-son-dakika',
    authDomain: 'amasya-son-dakika.firebaseapp.com',
    storageBucket: 'amasya-son-dakika.firebasestorage.app',
  );

}